name: Deploy coverage to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-coverage:
    runs-on: ubuntu-latest

    steps:
    # Récupère le dernier artifact htmlcov généré par tests.yml
    - name: Download coverage artifact
      uses: actions/download-artifact@v4
      with:
        name: htmlcov
        path: coverage/

    # Structure attendue par GitHub Pages
    - name: Prepare Pages folder
      run: |
        mkdir -p public/coverage
        cp -R coverage/* public/coverage/

    # Upload sur GitHub Pages
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  # Publication finale sur Pages
  deploy:
    needs: publish-coverage
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
    - name: Deploy GitHub Pages site
      id: deploy-pages
      uses: actions/deploy-pages@v4

